apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ok-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  backend:
    serviceName: ok-app
    servicePort: 80
  rules:
  - host: arch.homework
    http:
      paths:
        - path: /(.+)
          pathType: Prefix
          backend:
            service:
              name: "ok-app"
              port:
                number: 80
        - path: /otusapp/mikhail/(.+)
          pathType: Prefix
          backend:
            service:
              name: "ok-app"
              port:
                number: 80
